# coding:utf-8

# Crawler设置
max_redirect: 10        # 请求URL时允许的最大重定向深度
max_tasks: 20           # 最大的工作数量(线程）

# 反爬虫机制策略

# sleep time（单位: s）
sleep_time: 0

# cookies
# cookies: cookies file path

# 免费IP代理列表
# proxies: list

# headers（提供随机User-Agent）,模拟浏览器请求
# headers: dict